---
title: "LittorinaVisualisation"
author: "Ffion Titmuss"
date: "3/6/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

setwd("~/Repos/LittorinaThermal2019")

## Load packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Load data
```{r}
litt <- read.csv("./data/LittorinaData.csv")
resp <- read.csv("./data/RespirationData.csv")

mortData_all <- litt %>%
  rename(Spp = Genus_Species) %>%
  mutate(Spp = replace(Spp, Spp == "littorina_littorea", "LL")) %>%
  mutate(Spp = replace(Spp, Spp == "littorina_obtusata", "LO")) %>%
  mutate(Spp = replace(Spp, Spp == "littorina_saxatilis", "LS")) %>%
  mutate(SampleID = as.character(SampleID)) %>%
  mutate(Trt = factor(Trt, levels = c("HS", "NT", "CS")))

mortData <- mortData_all %>%
  filter(PreTrtMortNotes == "")
```

## Plot B1 mortality
```{r}
mortB1 <- mortData %>%
  filter(Block == 1) %>%
  rename("24" = TrtDay1_Survived,
         "48" = Day2_Survived,
         "51" = TrtDay3_Survived) %>%
  mutate("0" = TRUE) %>%
  gather("0", "24", "48", "51", key = "Time_hrs", value = "Survived") %>%
  mutate(Time_hrs = as.integer(Time_hrs),
         Surv_Int = as.integer(Survived),
         Tot_Int = 1) %>%
  group_by(Spp, PopID, Trt, Time_hrs) %>%
  summarise(Surv = sum(Surv_Int), Tot = sum(Tot_Int)) %>%
  mutate(Percent_Surv = Surv/Tot)

ggplot(mortB1, aes(x = Time_hrs,
                   y = Percent_Surv,
                   group = interaction(PopID, Trt),
                   shape = PopID,
                   linetype = PopID,
                   colour = Trt)) +
  geom_line() +
  geom_point() +
  labs(x = "Hours",
       y = "Percent Survival",
       title = "Block 1 Survival Post-Exposure") +
  scale_x_continuous(breaks = seq(0, 51, by = 25)) +
  ylim(0, 1) +
  scale_shape_manual(name = "Population",
                     labels = c("Northern", "Southern"),
                     values = c(19, 1)) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  scale_colour_manual(name = "Treatment",
                      labels = c("Heat", "Ambient", "Cold"),
                      values = c("orangered", "black", "dodgerblue")) +
  guides(shape = guide_legend(order = 1),
         linetype = guide_legend(order = 1)) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```

## Plot B2 mortality
```{r}
mortB2 <- mortData %>%
  filter(Block == 2) %>%
  rename("24" = TrtDay1_Survived, "48" = TrtDay2_Survived) %>%
  mutate("0" = TRUE) %>%
  gather("0", "24", "48", key = "Time_hrs", value = "Survived") %>%
  mutate(Time_hrs = as.integer(Time_hrs),
         Surv_Int = as.integer(Survived),
         Tot_Int = 1) %>%
  group_by(Block, Spp, PopID, Trt, Time_hrs) %>%
  summarise(Surv = sum(Surv_Int), Tot = sum(Tot_Int)) %>%
  mutate(Percent_Surv = Surv/Tot)

ggplot(mortB2, aes(x = Time_hrs,
                   y = Percent_Surv,
                   group = interaction(PopID, Trt),
                   shape = PopID,
                   linetype = PopID,
                   colour = Trt)) +
  geom_line() +
  geom_point() +
  labs(x = "Hours",
       y = "Percent Survival",
       title = "Block 2 Survival Post-Exposure") +
  ylim(0, 1) +
  scale_x_continuous(breaks = c(0, 24, 48)) +
  scale_shape_manual(name = "Population",
                     labels = c("Northern", "Southern"),
                     values = c(19, 1)) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  scale_colour_manual(name = "Treatment",
                      labels = c("Heat", "Ambient", "Cold"),
                      values = c("orangered", "black", "dodgerblue")) +
  guides(shape = guide_legend(order = 1),
         linetype = guide_legend(order = 1)) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```

## Plot B3 mortality
```{r}
mortB3 <- mortData %>%
  filter(Block == 3) %>%
  rename("24" = TrtDay1_Survived, "48" = TrtDay2_Survived) %>%
  mutate("0" = TRUE) %>%
  gather("0", "24", "48", key = "Time_hrs", value = "Survived") %>%
  mutate(Time_hrs = as.integer(Time_hrs),
         Surv_Int = as.integer(Survived),
         Tot_Int = 1) %>%
  group_by(Block, Spp, PopID, Trt, Time_hrs) %>%
  summarise(Surv = sum(Surv_Int), Tot = sum(Tot_Int)) %>%
  mutate(Percent_Surv = Surv/Tot)

ggplot(mortB3, aes(x = Time_hrs,
                   y = Percent_Surv,
                   group = interaction(PopID, Trt),
                   shape = PopID,
                   linetype = PopID,
                   colour = Trt)) +
  geom_line() +
  geom_point() +
  labs(x = "Hours",
       y = "Percent Survival",
       title = "Block 3 Survival Post-Exposure") +
  ylim(0, 1) +
  scale_x_continuous(breaks = c(0, 24, 48)) +
  scale_shape_manual(name = "Population",
                     labels = c("Northern", "Southern"),
                     values = c(19, 1)) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  scale_colour_manual(name = "Treatment",
                      labels = c("Heat", "Ambient", "Cold"),
                      values = c("orangered", "black", "dodgerblue")) +
  guides(shape = guide_legend(order = 1),
         linetype = guide_legend(order = 1)) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```


## Plot B2&3 mortality
```{r}
mortB23_ungrouped <- mortData %>%
  filter(Block == 2 | Block == 3) %>%
  mutate(Block = as.factor(Block))

mortB23 <- mortB23_ungrouped %>%
  rename("24" = TrtDay1_Survived, "48" = TrtDay2_Survived) %>%
  mutate("0" = TRUE) %>%
  gather("0", "24", "48", key = "Time_hrs", value = "Survived") %>%
  mutate(Time_hrs = as.integer(Time_hrs),
         Surv_Int = as.integer(Survived),
         Tot_Int = 1) %>%
  group_by(Spp, PopID, Trt, Time_hrs) %>%
  summarise(Surv = sum(Surv_Int), Tot = sum(Tot_Int)) %>%
  mutate(Percent_Surv = Surv/Tot)

ggplot(mortB23, aes(x = Time_hrs,
                    y = Percent_Surv,
                    group = interaction(PopID, Trt),
                    shape = PopID,
                    linetype = PopID,
                    colour = Trt)) +
  geom_line() +
  geom_point() +
  labs(x = "Hours",
       y = "Percent Survival",
       title = "Post-Exposure Survival") +
  ylim(0, 1) +
  scale_x_continuous(breaks = c(0, 24, 48)) +
  scale_shape_manual(name = "Population",
                     labels = c("Northern", "Southern"),
                     values = c(19, 1)) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  scale_colour_manual(name = "Treatment",
                      labels = c("Heat", "Ambient", "Cold"),
                      values = c("orangered", "black", "dodgerblue")) +
  guides(shape = guide_legend(order = 1),
         linetype = guide_legend(order = 1)) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```

## Plot gradient variation
```{r}
mortB23_24 <- mortB23 %>%
  filter(Trt == "HS" | Trt == "CS") %>%
  filter(Time_hrs == 24) %>%
  mutate(Trt = factor(Trt, levels = c("CS", "HS")))

ggplot(mortB23_24, aes(x = Trt, y = Percent_Surv, colour = PopID, group = PopID)) +
  geom_point() +
  geom_line() +
  ylim(0, 1) +
  labs(x = "Environment",
       y = "Percent Survival",
       title = "Post-Exposure (24h) Survival by Environment") +
  scale_x_discrete(labels = c("Cold", "Hot")) +
  scale_colour_manual(name = "Population",
                      labels = c("Northern", "Southern"),
                      values = c("#7CAE00", "#C77CFF")) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))

mortB23_48 <- mortB23 %>%
  filter(Trt == "HS" | Trt == "CS") %>%
  filter(Time_hrs == 48) %>%
  mutate(Trt = factor(Trt, levels = c("CS", "HS")))

ggplot(mortB23_48, aes(x = Trt, y = Percent_Surv, colour = PopID, group = PopID)) +
  geom_point() +
  geom_line() +
  ylim(0, 1) +
  labs(x = "Environment",
       y = "Percent Survival",
       title = "Post-Exposure (48h) Survival by Environment") +
  scale_x_discrete(labels = c("Cold", "Hot")) +
  scale_colour_manual(name = "Population",
                      labels = c("Northern", "Southern"),
                      values = c("#7CAE00", "#C77CFF")) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```

## Plot size vs. mortality
```{r}
sizeMort <- mortB23_ungrouped %>%
  mutate(DaysAlive = ifelse(TrtDay2_Survived == TRUE, 2, ifelse(TrtDay1_Survived == TRUE, 1, 0))) %>%
  mutate(DaysAlive = as.factor(DaysAlive))

sizeMort$DaysAlive <- factor(sizeMort$DaysAlive, levels = c(2, 1, 0))

ggplot(sizeMort, aes(x = WetWeight, fill = Trt)) +
  geom_histogram() +
  facet_grid(DaysAlive ~ ., switch = "y") +
  labs(x = "Wet Weight (g)",
       y = "Days Alive",
       title = "Survival vs. Weight") +
  scale_fill_manual(name = "Treatment",
                    labels = c("Heat", "Ambient", "Cold"),
                    values = c("orangered", "black", "dodgerblue")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"))

## Facet by Spp

ggplot(sizeMort, aes(x = WetWeight, fill = Trt)) +
  geom_histogram() +
  facet_grid(DaysAlive ~ Spp, switch = "y", labeller = labeller(Spp = c(LL = "L. littorea", LO = "L. obtusata", LS = "L. saxatilis"))) +
  labs(x = "Wet Weight (g)",
       y = "Days Alive",
       title = "Survival vs. Weight") +
  scale_fill_manual(name = "Treatment",
                    labels = c("Heat", "Ambient", "Cold"),
                    values = c("orangered", "black", "dodgerblue")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text.x = element_text(face = "italic"))

sizeMortLL <- sizeMort %>%
  filter(Spp == "LL")

ggplot(sizeMortLL, aes(x = WetWeight, fill = Trt)) +
  geom_histogram() +
  facet_grid(DaysAlive ~ ., switch = "y") +
  labs(x = "Wet Weight (g)",
       y = "Days Alive",
       title = "L. littorea Survival vs. Weight") +
  scale_fill_manual(name = "Treatment",
                    labels = c("Heat", "Ambient", "Cold"),
                    values = c("orangered", "black", "dodgerblue")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"))

sizeMortLO <- sizeMort %>%
  filter(Spp == "LO")

ggplot(sizeMortLO, aes(x = WetWeight, fill = Trt)) +
  geom_histogram() +
  facet_grid(DaysAlive ~ ., switch = "y") +
  labs(x = "Wet Weight (g)",
       y = "Days Alive",
       title = "L. obtusata Survival vs. Weight") +
  xlim(0, 3) +
  scale_fill_manual(name = "Treatment",
                    labels = c("Heat", "Ambient", "Cold"),
                    values = c("orangered", "black", "dodgerblue")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"))

sizeMortLS <- sizeMort %>%
  filter(Spp == "LS")

ggplot(sizeMortLS, aes(x = WetWeight, fill = Trt)) +
  geom_histogram() +
  facet_grid(DaysAlive ~ ., switch = "y") +
  labs(x = "Wet Weight (g)",
       y = "Days Alive",
       title = "L. saxatilis Survival vs. Weight") +
  xlim(0, 3) +
  scale_fill_manual(name = "Treatment",
                    labels = c("Heat", "Ambient", "Cold"),
                    values = c("orangered", "black", "dodgerblue")) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line = element_line(colour = "black"))
```

## Plot mortality with respect to respiration
```{r}
mort_resp <- mort_resp_all %>%
  filter(PreTrtMortNotes == "" | PreTrtMortNotes == "wrong spp, orig.
         labeled littorina_saxatilis") %>%
  mutate(Trt = factor(Trt, levels = c("HS", "NT", "CS")))

ggplot(mort_resp, aes(x = TrtDay2_Survived,
                      y = RespPerG,
                      colour = Trt,
                      linetype = PopID)) +
  geom_boxplot(position = position_dodge2(preserve = "single")) +
  labs(x = "Post-Exposure Survival",
       y = "Respiration (umol O2 / hr / g wet weight)",
       title = "Block 3 Samples") +
  scale_x_discrete(limits = c(TRUE, FALSE), labels = c("Alive", "Dead")) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  scale_colour_manual(name = "Treatment",
                      labels = c("42C, 46C", "21C, 20C", "-12C, -12C"),
                      values = c("orangered", "black", "dodgerblue")) +
  facet_grid(. ~ Spp,
              labeller = labeller(Spp = c(LL = "L. littorea",
                                          LO = "L. obtusata",
                                          LS = "L. saxatilis"))) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        strip.text = element_text(face = "italic"))
```

## Plot respiration/weight variation
```{r}
respData <- resp %>%
  filter(!is.na(Block)) %>%
  rename(MaxRate = MaxRespRate_umolO2.hr) %>%
  mutate(Spp = as.factor(str_extract(SampleID, "L[LOS]"))) %>%
  mutate(SampleN = as.integer(as.character(SampleN))) %>%
  mutate(SampleID = as.character(SampleID))

mort_resp_all <- right_join(mortData_all, respData) %>%
  mutate(RespPerG = MaxRate / WetWeight)

ggplot(mort_resp_all, aes(x = Spp,
                          y = RespPerG,
                          colour = Spp,
                          linetype = PopID)) +
  geom_boxplot() +
  labs(x = "Species",
       y = "Respiration (umol O2 / hr / g wet weight)",
       title = "Respiration Rate Distribution of Block 3 Samples") +
  scale_x_discrete(labels = c("L. littorea",
                              "L. obtusata",
                              "L. saxatilis")) +
  scale_linetype_discrete(name = "Population",
                          labels = c("Northern", "Southern")) +
  guides(colour = FALSE) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(colour = "black"),
        axis.text.x = element_text(face = "italic"))
```
